version: "4.31"

services:
  api:
    image: node:18
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - "3000:3000"
    networks:
      - backend-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  db-postgres:
    image: postgres:16.3-alpine3.19
    ports:
      - "5432:5432"
    networks:
      - backend-network
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=adminuser
      - PG_DATA=/var/lib/postgresql/data
      - POSTGRES_DB=qrmdb

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: start-dev
    networks:
      - backend-network

networks:
  backend-network:
